python -u run.py \
  --task_name anomaly_detection \
  --is_training 1 \
  --root_path ./dataset/RedTide \
  --model_id RedTide \
  --model DLinear \
  --data PSM \
  --features M \
  --seq_len 24 \
  --pred_len 0 \
  --d_model 128 \
  --d_ff 128 \
  --e_layers 3 \
  --enc_in 14 \
  --c_out 14 \
  --anomaly_ratio 1 \
  --batch_size 128 \
  --train_epochs 3